"""Initial Migration

Revision ID: 0754f1ac9676
Revises: 5a828b63d916
Create Date: 2022-05-11 16:14:55.869368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0754f1ac9676'
down_revision = '5a828b63d916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
